apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/mlops-chart
    repoURL: 'https://github.com/sagarshrestha24/mlops.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
