name: Ci/CD for Gliner App
on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to the container registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(git rev-parse --short=5 HEAD)
          IMAGE=${{ secrets.REGISTRY_USERNAME }}/${{ secrets.IMAGE_NAME }}:$IMAGE_TAG

          # Build the Docker image
          docker build -t $IMAGE .

          # Push the Docker image
          docker push $IMAGE

          # Output the image tag for later steps
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Update the Helm chart with the new image tag
      - name: Update Helm Chart Image Tag
        run: |
          CHART_PATH="charts/mlops-chart/values.yaml"  # Replace with your Helm chart's values.yaml path

          # Update the image tag in the Helm chart
          sed -i "s|tag:.*|tag: $IMAGE_TAG|" $CHART_PATH

          git config user.name "sagarshrestha24"
          git config user.email "kobesagar24@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add $CHART_PATH
          git commit -m "Update Helm chart image tag to $IMAGE"
          git push origin main
