name: Ci/CD for Gliner App
on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to the container registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(git rev-parse --short=5 HEAD)
          IMAGE=${{ secrets.REGISTRY_USERNAME }}/${{ secrets.IMAGE_NAME }}:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: test
    needs: 
      - build
    steps:
      - name: Branch Tag Action
        uses: nimblehq/branch-tag-action@v1.2

      - name: Notify infra repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: "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"
          repository: sagarshrestha24/argo-cd
          event-type: image-published
          client-payload: |
            {
              "service": "mbmstudio",
              "tag": "$IMAGE_TAG",
              "env": "test"
            }
